name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install tooling
        run: make tooling
      
      - name: Tests
        run: make test

      - name: Linting
        run: make lint

      # Disable for now until coverage meets
      # minimum standard.
      # - name: Coverage
      #   run: make check-coverage
